language: haskell-multi-ghc

env:
  - GHCVER=7.6.3 CABALVER=1.18
  - GHCVER=7.8.4 CABALVER=1.18
  - GHCVER=7.8.4 CABALVER=1.18 STACKAGESNAPSHOT=lts-2.22
  - GHCVER=7.10.2 CABALVER=1.22
  - GHCVER=7.10.2 CABALVER=1.22 STACKAGESNAPSHOT=lts-3.0
  - GHCVER=7.10.2 CABALVER=1.22 STACKAGESNAPSHOT=lts-3.22
  - GHCVER=7.10.3 CABALVER=1.22
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-4.0
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-4.2
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-5.0
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-5.18
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-6.0
  - GHCVER=7.10.3 CABALVER=1.22 STACKAGESNAPSHOT=lts-6.5
  - GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=cabal.1.config NOTESTS=YES
  - GHCVER=8.0.1 CABALVER=1.24
  - GHCVER=head CABALVER=1.22

matrix:
  fast_finish: true
  allow_failures:
    - env: GHCVER=head CABALVER=1.22

branches:
  only:
    - master
